/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package currencyconverter;

import currencyconverter.Logic.Calculation;
import currencyconverter.Logic.Logic;
import currencyconverter.Model.ModelProgram;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Currency extends javax.swing.JFrame {
	
	/**
	 * Creates new form Login
	 */
	public Currency() {
		initComponents();
		setLocationRelativeTo(this);
	}
	
	String name;
	public Currency(String name) {
		initComponents();
		Logic logic = new Logic();
		label_result.setText(logic.output);
		this.name = name;
		label_name.setText(name);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        cb_input = new javax.swing.JComboBox<>();
        tf_input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_output = new javax.swing.JComboBox<>();
        btn_convert = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        label_result = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(462, 458));
        setMinimumSize(new java.awt.Dimension(462, 458));
        setUndecorated(true);

        jPanel2.setMaximumSize(new java.awt.Dimension(462, 458));
        jPanel2.setMinimumSize(new java.awt.Dimension(462, 458));
        jPanel2.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Select your Input Currency :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(230, 100, 230, 16);

        label_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_name.setToolTipText("");
        label_name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(label_name);
        label_name.setBounds(40, 80, 110, 10);

        cb_input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "‏‏‎ ‎", "Rupiah", "Euro", "Dollar", "Yen" }));
        jPanel2.add(cb_input);
        cb_input.setBounds(228, 120, 90, 30);

        tf_input.setText("0");
        tf_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_inputKeyPressed(evt);
            }
        });
        jPanel2.add(tf_input);
        tf_input.setBounds(320, 120, 110, 30);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Select your Output Currency :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(230, 160, 230, 16);

        cb_output.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "‏‏‎ ‎", "Rupiah", "Euro", "Dollar", "Yen" }));
        jPanel2.add(cb_output);
        cb_output.setBounds(228, 180, 90, 30);

        btn_convert.setForeground(new java.awt.Color(102, 102, 0));
        btn_convert.setText("Convert");
        btn_convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertActionPerformed(evt);
            }
        });
        jPanel2.add(btn_convert);
        btn_convert.setBounds(320, 180, 110, 30);

        jLabel4.setText("Converted Amount :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(140, 280, 220, 16);

        label_result.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_result.setText("-");
        jPanel2.add(label_result);
        label_result.setBounds(330, 280, 90, 16);

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(102, 102, 0));
        btn_clear.setText("Clear");
        btn_clear.setMaximumSize(new java.awt.Dimension(74, 32));
        btn_clear.setMinimumSize(new java.awt.Dimension(74, 32));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clear);
        btn_clear.setBounds(230, 310, 80, 40);

        btn_exit.setForeground(new java.awt.Color(102, 102, 0));
        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel2.add(btn_exit);
        btn_exit.setBounds(380, 420, 70, 32);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/currencyconverter/christ1.jpg"))); // NOI18N
        jPanel2.add(background);
        background.setBounds(0, 0, 462, 458);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertActionPerformed
		// TODO add your handling code here:
		String a = (String) cb_input.getSelectedItem();
		String b = (String) cb_output.getSelectedItem();
		String enterInput = tf_input.getText();
		
		Logic logic = new Logic();
		ModelProgram modelProgram = new ModelProgram();
		
		clear();
		
		int input = Integer.parseInt(enterInput);

		modelProgram.setInput(input);
		
		Calculation calculation = new Calculation();
		
		if (a.equals("Rupiah") && b.equals("Rupiah")) {
			String result = logic.idr_to_idr(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Rupiah") && b.equals("Euro")) {
			String result = logic.idr_to_eur(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Rupiah") && b.equals("Dollar")) {
			String result = logic.idr_to_usd(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Rupiah") && b.equals("Yen")) {
			String result = logic.idr_to_jpy(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Euro") && b.equals("Euro")) {
			String result = logic.eur_to_eur(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Euro") && b.equals("Rupiah")) {
			String result = logic.eur_to_idr(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Euro") && b.equals("Dollar")) {
			String result = logic.eur_to_usd(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Euro") && b.equals("Yen")) {
			String result = logic.eur_to_jpy(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Dollar") && b.equals("Dollar")) {
			String result = logic.usd_to_usd(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Dollar") && b.equals("Rupiah")) {
			String result = logic.usd_to_idr(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Dollar") && b.equals("Euro")) {
			String result = logic.usd_to_eur(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Dollar") && b.equals("Yen")) {
			String result = logic.usd_to_jpy(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Yen") && b.equals("Yen")) {
			String result = logic.jpy_to_jpy(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Yen") && b.equals("Rupiah")) {
			String result = logic.jpy_to_idr(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Yen") && b.equals("Euro")) {
			String result = logic.jpy_to_eur(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Yen") && b.equals("Dollar")) {
			String result = logic.jpy_to_usd(modelProgram);
			label_result.setText(result);
		}
		
		tf_input.setText(enterInput);
    }//GEN-LAST:event_btn_convertActionPerformed

    private void tf_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_inputKeyPressed
		// TODO add your handling code here:
    }//GEN-LAST:event_tf_inputKeyPressed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
		// TODO add your handling code here:
		clear();
    }//GEN-LAST:event_btn_clearActionPerformed
	
	void clear(){
		ModelProgram modelProgram = new ModelProgram();

		modelProgram.setInput(0);

		tf_input.setText("0");
		label_result.setText("0");
		tf_input.requestFocus();
	}
	
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
		// TODO add your handling code here:
		int dialog = JOptionPane.showOptionDialog(this, "Are you sure?", "Exit",
				JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

		if (dialog == JOptionPane.YES_OPTION) {
			JOptionPane.showMessageDialog(this, "Thank you for using this program");
			System.exit(0);
		}
    }//GEN-LAST:event_btn_exitActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Currency().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_convert;
    private javax.swing.JButton btn_exit;
    private javax.swing.JComboBox<String> cb_input;
    private javax.swing.JComboBox<String> cb_output;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_result;
    private javax.swing.JTextField tf_input;
    // End of variables declaration//GEN-END:variables
}
